config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students do
    collection do
      get 'search', to: 'students#search'
    end
  end
  resources :courses do
    collection do
      get 'search', to: 'courses#search'
    end
  end
  resources :sections do
    collection do
      get 'search', to:'sections#search'
    end
  end
  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

  validates_uniqueness_of :name, :number
  validates_presence_of :name, :number, :department, :credit_hours

  has_many :sections
end

app/models/section.rb
class Section < ApplicationRecord

  validates :number, uniqueness: { scope: :course, message: "only one section" }
  validates_presence_of :number, :semester,  :course_id, :room_number

  belongs_to :course
  has_and_belongs_to_many :students

  def desc
    "#{course.department} #{course.name} - #{number}"
  end

end

app/models/student.rb
class Student < ApplicationRecord

  validates_presence_of :first_name, :last_name

  has_and_belongs_to_many :sections
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  def search
    @courses = Course.where("name like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :department, :number, :credit_hours, :query)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @students = Student.all
  end

  # GET /sections/1/edit
  def edit
  end

  def search
    @sections = Section.where("semester like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /sections
  # POST /sections.json
  def create

    @section = Section.new(section_params)
    @student.sections.append(student_params[:section_ids])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      if params[:section].is_a? String
        params[:section]
      else
        params.require(:section).permit(:semester, :number, :course_id, :room_number, :query, { student_ids: [] })
      end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  def search
    @students = Student.where("first_name like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /students
  # POST /students.json
  def create

    #student_params[:section_ids] ||= []

    @student = Student.new(student_params)
    @student.sections.append(student_params[:section_ids])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      if params[:student].is_a? String
        params[:students]
      else
        params.require(:student).permit(:first_name, :last_name, :query, {section_ids: []})
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :credit_hours %>
    <%= form.number_field :credit_hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="container">
  <div class="container">
      <%= form_tag(search_courses_url, method: "get") do %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search")%>
      <%  end %>
  </div>
</div>

<section class="section">
  <div class="container">
    <h2 class="title">Courses</h2>

    <table class="table is-hoverable is-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Department</th>
          <th>Number</th>
          <th>Credit hours</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= course.name %></td>
            <td><%= course.department %></td>
            <td><%= course.number %></td>
            <td><%= course.credit_hours %></td>
            <td><%= link_to 'Show', course %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <button class="button"><%= link_to 'New Course', new_course_path %></button>
  </div>
</section>

app/views/courses/new.html.erb
<div class:"container">
  <h1 class="title">New Course</h1>
  <div class="box"><%= render 'form', course: @course %></div>
  <button class="button"><%= link_to 'Back', courses_path %></button>
</div>

app/views/courses/show.html.erb
<section class="hero">
  <div class="box">
    <div class="hero-head">
      <label class="title"><%= @course.name %></label>
    </div>
    <div class="hero-body">
      <div class="content">
        <div class="columns is-gapless">
          <div class="column is-4 is-offset-one">
            <label class="subtitle">Department:</label>
          </div>
          <div class="columns is-gapless">
            <div class="column">
              <label class="label has-text-weight-semibold"><%= @course.department %></label>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="columns is-gapless">
          <div class="column is-4 is-offset-one">
            <label class="subtitle">Number:</label>
          </div>
          <div class="column">
            <label class="label has-text-left has-text-weight-semibold"><%= @course.number %></label>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="columns is-gapless">
          <div class="column is-4 is-offset-one">
            <label class="subtitle">Credit Hours:</label>
          </div>
          <div class="column is-4 is-offset-one">
            <label class="label has-text-weight-semibold"><%= @course.credit_hours %></label>
          </div>
        </div>
      </div>
      <button class="button"><%= link_to 'Edit', edit_course_path(@course) %></button>
      <button class="button"><%= link_to 'Back', courses_path %></button>

    </div>

    <div class="hero-foot">
      <div class="columns">
        <div class="column is-5 is-offset-one"
        <% unless @course.sections.empty? %>
          <label class="subtitle">Sections:</label>
          <div class="content">
          <% @course.sections.each do |section| %>
            <div class="box"><%= link_to "Semester: #{section.semester} -> 00#{section.number}", section %></div>
          <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterBanner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <div class="container">
      <header class="navbar" role="navigation">
        <div id="navbarBetterBanner" class="navbar-menu">
          <div class="navbar-item">
            <%=link_to "Home", courses_path%>
          </div>
          <div class="navbar-item">
            <%= link_to "Sections", sections_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Students", students_path %>
          </div>
          <a class="navbar-item">
            About
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <a class="navbar-item">
                <strong>
                  <%= link_to "#{current_user.email}", edit_user_registration_path, :class => 'navbar-button'%>
                </strong>
              </a>

              <div class="button is-light">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-button' %>
              </div>
            <% else %>
              <a
            <div class="buttons">
              <div class="button is-primary">
                <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-button' %>
              </div>
              <div class="button is-light">
                <%= link_to "Login", new_user_session_path, :class => 'navbar-button' %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </header>
    </div>

    <%= yield %>
  </body>
</html>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :name, {prompt: 'Course'} %>
  </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number %>
  </div>

  <div class="field">
    <%= form.label :student_ids%>
    <%= form.collection_check_boxes :student_ids, Student.all, :id, :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <%= form_tag(search_sections_url, method: "get") do %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search")%>
    <%  end %>
</div>

<section class="section">

  <div class="container">
    <h2 class="title">Sections</h2>

    <table class="table is-hoverable is-bordered">
      <thead>
        <tr>
          <th>Semester</th>
          <th>Number</th>
          <th>Course</th>
          <th>Room number</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @sections.each do |section| %>
          <tr>
            <td><%= section.semester %></td>
            <td><%= section.number %></td>
            <td><%= section.course.name %></td>
            <td><%= section.room_number %></td>
            <td><%= link_to 'Show', section %></td>
            <td><%= link_to 'Edit', edit_section_path(section) %></td>
            <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>

  <button class="button"><%= link_to 'New Section', new_section_path %></button>
  </div>

</section>

app/views/sections/new.html.erb
<div class:"container">
  <h1 class="title">New Section</h1>
  <div class="box"><%= render 'form', section: @section %></div>
  <button class="button"><%= link_to 'Back', sections_path %></button>
</div>

app/views/sections/show.html.erb
<div class="container">
    <section class="hero">
      <div class="hero-head">
        <label class="title"><%= @section.course.name %></label>
      </div>
      <div class="hero-body">
        <div class="content">
          <div class="columns is-gapless">
            <div class="column is-4 is-offset-one">
              <label class="subtitle">Semester:</label>
            </div>
            <div class="columns is-gapless">
              <div class="column">
                <label class="label has-text-weight-semibold"><%= @section.semester %></label>
              </div>
            </div>
          </div>
        </div>
        <div class="content">
          <div class="columns is-gapless">
            <div class="column is-4 is-offset-one">
              <label class="subtitle">Number:</label>
            </div>
            <div class="column">
              <label class="label has-text-left has-text-weight-semibold"><%= "00#{@section.number}" %></label>
            </div>
          </div>
        </div>

        <div class="content">
          <div class="columns is-gapless">
            <div class="column is-4 is-offset-one">
              <label class="subtitle">Room number:</label>
            </div>
            <div class="column is-4 is-offset-one">
              <label class="label has-text-weight-semibold"><%= @section.room_number %></label>
            </div>
          </div>
        </div>

        <button class="button"><%= link_to 'Edit', edit_section_path(@section) %></button>
        <button class="button"><%= link_to 'Back', sections_path %></button>

      </div>
      <div class="hero-foot">
        <% unless @section.students.empty? %>
            <label class="subtitle">Students:</label>
            <% @section.students.each do |student| %>
            <label class="label"><%= student.last_name %></label>
            <% end %>
        <% end %>
      </div>
    </section>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes :section_ids, Section.all, :id, :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="container">
      <%= form_tag(search_students_url, method: "get") do %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search")%>
      <%  end %>
  </div>

  <div class="section">
    <div class="container">
      <h1 class="title">Students</h1>

      <table class="table">
        <thead class="thead">
          <tr class="tr">
            <th>First name</th>
            <th>Last name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td><%= student.first_name %></td>
              <td><%= student.last_name %></td>
              <td><%= link_to 'Show', student %></td>
              <td><%= link_to 'Edit', edit_student_path(student) %></td>
              <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Student', new_student_path %>
    </div>
 </div>

app/views/students/new.html.erb
<div class:"container">
  <h1 class="title">New Student</h1>
  <div class="box"><%= render 'form', student: @course %></div>
  <button class="button"><%= link_to 'Back', students_path %></button>
</div>

app/views/students/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

<div class="hero-foot">
  <% unless @student.sections.empty? %>
    <div class="box">
      <label class="subtitle">Students:</label>
      <% @student.sections.each do |section| %>
      <%= render section %>
      <% end %>
    </div>
  <% end %>
</div>